package com.miu.bookhub.inventory.repository.entity;

public enum Genre {
    ACTION_AND_ADVENTURE,
    CLASSICS,
    COMIC_OR_GRAPHIC_NOVEL,
    DETECTIVE_AND_MYSTERY,
    FANTASY,
    HISTORICAL_FICTION,
    HORROR,
    LITERARY_FICTION,
    ROMANCE,
    SIC_FI,
    SHORT_STORIES,
    SUSPENSE_AND_THRILLERS,
    COOK_BOOKS,
    ESSAYS,
    HISTORY,
    MEMOIR,
    POETRY,
    SELF_HELP,
    TRUE_CRIME,
    TECHNOLOGY
}
