server:
  port: 9000
spring:
  application:
    name: bookhub

  datasource:
    username: bookhub
    password: bookhub
    url: jdbc:postgresql://localhost:5432/bookhub

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
