server:
  port: 9000

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: bookhub

  datasource:
    username: bookhub
    password: bookhub
    url: jdbc:postgresql://localhost:5432/bookhub

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
